#!/bin/sh

__DIR__=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

. "${__DIR__}/find-repo-root.sh"

__REPOROOT__=`get_repo_root "${__DIR__}"`

_pnpm_binary="${__REPOROOT__}/common/temp/pnpm-local/node_modules/.bin/pnpm"

if [ ! -f "${_pnpm_binary}" ]; then
    echo "ERROR: pnpm binary not found at \"${_pnpm_binary}\"."
    echo "Have you run \"rush install\" or \"rush update\"?"
    exit 1
fi

for _arg in $@; do
    for _i in import install i install-test it; do
        if [ "$_arg" = "$_i" ]; then
            echo "ERROR: pnpm subcommand \"$_arg\" is known as incompatible with Rush."
            exit 1
        fi
    done
    for _i in add link ln remove rm unlink update up; do
        if [ "$_arg" = "$_i" ]; then
            echo "Warning: pnpm subcommand \"$_arg\" invalidates Rush state."
            echo "Run \"rush install\" or \"rush update\" afterwards."
        fi
    done
done

NPM_CONFIG_WORKSPACE_DIR="\"${__REPOROOT__}/common/temp\"" \
NPM_CONFIG_STORE_DIR="\"${__REPOROOT__}/common/temp/pnpm-store\"" \
    "${_pnpm_binary}" \
    $@
