#!/bin/sh

__DIR__=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

. "${__DIR__}/find-repo-root.sh"

__REPOROOT__=`get_repo_root "${__DIR__}"`

node "${__REPOROOT__}/common/scripts/install-run-rush.js" $@
